/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIS;

import Controlador.AccesoSistema;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import Controlador.*;
public class MenuSistema extends javax.swing.JFrame {

   int x,y ;Controlador basectr=new Controlador();public static String dniusuari="",codigousuario="";
    public MenuSistema() {
        initComponents();   this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
     LABELFECHA.setText(basectr.DevolverDatosSql("SELECT  FORMAT(CONVERT(DATE,GETDATE()),'d/M/yyyy');", 1));
     
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LABELFECHA = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LABELUSUARIO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PERFIL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemnuevousuarios = new javax.swing.JMenuItem();
        itemtipoproductos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemproductos = new javax.swing.JMenuItem();
        itemclientes = new javax.swing.JMenuItem();
        itemempleados = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        menuconsulta = new javax.swing.JMenu();
        itemconsultausuarios = new javax.swing.JMenuItem();
        itemconsultaprod = new javax.swing.JMenuItem();
        itemconsultaclientes = new javax.swing.JMenuItem();
        itemtrabajadores = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItemVENTADIA = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        procesos = new javax.swing.JMenu();
        itemventa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jcMousePanel1.setColor2(new java.awt.Color(255, 0, 0));
        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/índice.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("FECHA  :  ");

        LABELFECHA.setFont(new java.awt.Font("Arial Black", 0, 28)); // NOI18N
        LABELFECHA.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("USUARIO CONECTADO  : ");

        LABELUSUARIO.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        LABELUSUARIO.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("PERFÍL :  ");

        PERFIL.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        PERFIL.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELFECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PERFIL, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(LABELFECHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LABELUSUARIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PERFIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/logo.png"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.setLayer(jcMousePanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        jMenu1.setText("Mantenimientos");
        jMenu1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        itemnuevousuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        itemnuevousuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/usuario.png"))); // NOI18N
        itemnuevousuarios.setText("Nuevo Usuario");
        itemnuevousuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnuevousuariosActionPerformed(evt);
            }
        });
        jMenu1.add(itemnuevousuarios);

        itemtipoproductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        itemtipoproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Box_1.png"))); // NOI18N
        itemtipoproductos.setText("Tipo Producto");
        itemtipoproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemtipoproductosActionPerformed(evt);
            }
        });
        jMenu1.add(itemtipoproductos);
        jMenu1.add(jSeparator1);

        itemproductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        itemproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-icon.png"))); // NOI18N
        itemproductos.setText("Productos");
        itemproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemproductosActionPerformed(evt);
            }
        });
        jMenu1.add(itemproductos);

        itemclientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes_1.png"))); // NOI18N
        itemclientes.setText("Clientes");
        itemclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemclientesActionPerformed(evt);
            }
        });
        jMenu1.add(itemclientes);

        itemempleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        itemempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vendedor_1.png"))); // NOI18N
        itemempleados.setText("Trabajadores");
        itemempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemempleadosActionPerformed(evt);
            }
        });
        jMenu1.add(itemempleados);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recordar pasword.png"))); // NOI18N
        jMenuItem1.setText("Cerrar Seción");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jMenuItem15.setText("Salir del Sistema");
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        menuconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/base.png"))); // NOI18N
        menuconsulta.setText("Consultas");
        menuconsulta.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        itemconsultausuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/usuario.png"))); // NOI18N
        itemconsultausuarios.setText("Usuarios");
        itemconsultausuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemconsultausuariosActionPerformed(evt);
            }
        });
        menuconsulta.add(itemconsultausuarios);

        itemconsultaprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir compra.png"))); // NOI18N
        itemconsultaprod.setText("Productos");
        itemconsultaprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemconsultaprodActionPerformed(evt);
            }
        });
        menuconsulta.add(itemconsultaprod);

        itemconsultaclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes_1.png"))); // NOI18N
        itemconsultaclientes.setText("Clientes");
        itemconsultaclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemconsultaclientesActionPerformed(evt);
            }
        });
        menuconsulta.add(itemconsultaclientes);

        itemtrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vendedor.png"))); // NOI18N
        itemtrabajadores.setText("Trabajadores");
        itemtrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemtrabajadoresActionPerformed(evt);
            }
        });
        menuconsulta.add(itemtrabajadores);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Box.png"))); // NOI18N
        jMenuItem2.setText("Categorias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuconsulta.add(jMenuItem2);

        jMenuBar1.add(menuconsulta);

        Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte3.png"))); // NOI18N
        Reportes.setText("Reportes");
        Reportes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/boletass.png"))); // NOI18N
        jMenuItem12.setText("Ventas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        Reportes.add(jMenuItem12);

        jMenuItemVENTADIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/list_notes_930.png"))); // NOI18N
        jMenuItemVENTADIA.setText("Reporte diario");
        jMenuItemVENTADIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVENTADIAActionPerformed(evt);
            }
        });
        Reportes.add(jMenuItemVENTADIA);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/PAGO 2.png"))); // NOI18N
        jMenuItem3.setText("Ganancias");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Reportes.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/editnote_pencil_edi_6175.png"))); // NOI18N
        jMenuItem4.setText("Consulta venta");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Reportes.add(jMenuItem4);

        jMenuBar1.add(Reportes);

        procesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/venta medic.png"))); // NOI18N
        procesos.setText("Proceso");
        procesos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        itemventa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        itemventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/venta medic.png"))); // NOI18N
        itemventa.setText("Ventas ");
        itemventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemventaActionPerformed(evt);
            }
        });
        procesos.add(itemventa);

        jMenuBar1.add(procesos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
      x=evt.getX();y=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
    Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void itemnuevousuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnuevousuariosActionPerformed
        NewUser nuevouser=new NewUser(this, rootPaneCheckingEnabled);nuevouser.setVisible(true);
    }//GEN-LAST:event_itemnuevousuariosActionPerformed

    private void itemconsultausuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemconsultausuariosActionPerformed
     Usuarios usua=new Usuarios(this, rootPaneCheckingEnabled);usua.setVisible(true);
    }//GEN-LAST:event_itemconsultausuariosActionPerformed

    private void itemtipoproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemtipoproductosActionPerformed
       Categorias cate=new Categorias(this, rootPaneCheckingEnabled);cate.setVisible(true);
    }//GEN-LAST:event_itemtipoproductosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
   dispose(); Logín log=new Logín();log.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemproductosActionPerformed
      Productos produc=new Productos(this, rootPaneCheckingEnabled);produc.setVisible(true);
    }//GEN-LAST:event_itemproductosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       categoriaconsulta ctc=new categoriaconsulta(this, rootPaneCheckingEnabled);ctc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void itemconsultaprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemconsultaprodActionPerformed
        // TODO add your handling code here:
        ConsultaProductos cp=new ConsultaProductos(this, rootPaneCheckingEnabled);cp.setVisible(true);
    }//GEN-LAST:event_itemconsultaprodActionPerformed

    private void itemempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemempleadosActionPerformed
      Empleados emp=new Empleados(this, rootPaneCheckingEnabled);
      emp.setVisible(true);
    }//GEN-LAST:event_itemempleadosActionPerformed

    private void itemclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemclientesActionPerformed
    Clientes cl=new Clientes(this, rootPaneCheckingEnabled);cl.setVisible(true);
    }//GEN-LAST:event_itemclientesActionPerformed

    private void itemventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemventaActionPerformed
       Ventas v=new Ventas(this, false);v.setVisible(true);
    }//GEN-LAST:event_itemventaActionPerformed

    private void itemtrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemtrabajadoresActionPerformed
      ConsultaEmpleados ce=new ConsultaEmpleados(this, rootPaneCheckingEnabled);
      ce.setVisible(true);
    }//GEN-LAST:event_itemtrabajadoresActionPerformed

    private void itemconsultaclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemconsultaclientesActionPerformed
      ConsultaClientes cl=new ConsultaClientes(this, rootPaneCheckingEnabled);cl.setVisible(true);
    }//GEN-LAST:event_itemconsultaclientesActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
      FACTURAS fac=new FACTURAS(this, false);fac.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItemVENTADIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVENTADIAActionPerformed
        // TODO add your handling code here:
//        VentaDia V=new VentaDia(this, false);V.setVisible(true);
VentaDia dia=new VentaDia();
dia.show();
    }//GEN-LAST:event_jMenuItemVENTADIAActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        GANANCIAS uti = new GANANCIAS();
        uti.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FRM_CONSULTA_VENTAS ventas = new FRM_CONSULTA_VENTAS();
       ventas.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABELFECHA;
    public static javax.swing.JLabel LABELUSUARIO;
    public static javax.swing.JLabel PERFIL;
    public static javax.swing.JMenu Reportes;
    public static javax.swing.JMenuItem itemclientes;
    public static javax.swing.JMenuItem itemconsultaclientes;
    public static javax.swing.JMenuItem itemconsultaprod;
    public static javax.swing.JMenuItem itemconsultausuarios;
    public static javax.swing.JMenuItem itemempleados;
    public static javax.swing.JMenuItem itemnuevousuarios;
    public static javax.swing.JMenuItem itemproductos;
    public static javax.swing.JMenuItem itemtipoproductos;
    public static javax.swing.JMenuItem itemtrabajadores;
    public static javax.swing.JMenuItem itemventa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemVENTADIA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    public static javax.swing.JMenu menuconsulta;
    public static javax.swing.JMenu procesos;
    // End of variables declaration//GEN-END:variables
}
